### PR TITLE
Added missing references to EEIP project.

### PR DESCRIPTION
**Pull request by rtigithub**
Added missing references to EEIP project.
Specified build dependencies.

I am using VS2019 so the changes to the .sln file should not be automatically merged.

### CODE REVIEW

**Comment by ngbrown** [comment]
This patch doesn't add the `<ProjectReference/>` tag to each project that is really needed.

Please see https://github.com/ngbrown/EEIP.NET/commit/dae7956594534862057712e7a4a0b531c7d97e24 for a more complete solution.

**Comment by rtigithub** [comment]
Thank you for reviewing.  From what I can tell the correct reference already exists in most of the projects in the current rossmann-engineering:master branch, except for the two in this pull request.

**Comment by rtigithub** [comment]
@ngbrown Thank you.  This really helps.  I will merge your code into our fork.  So the `<Reference />` tag should be removed, and replaced with the correct `<ProjectReference />`?

Is Ross-Engineering still maintaining this repository, and responding to pull requests?  Or is your fork considered the more active?

**Comment by TheColonel2688** [comment]
It doesn't look like @rossmann-engineering maintains this anymore. We may want to look at picking someone's fork, and continuing to maintain this our selves. Or create a new github organization and for it to that. Then maintain it from there.

**Comment by rossmann-engineering** [comment]
The project is still active and maintained, of course sometimes more sometimes less depending on the time I am able to spend.

**Comment by ngbrown** [comment]
@rtigithub it looks like you didn't update the branch for this pull request with the `<ProjectReference />` changes, and now it is merged.

**Comment by TheColonel2688** [comment]
ugh

**Comment by rtigithub** [comment]
@ngbrown Since rossmann-engineering is still being maintained, will you issue a pull request with your recommended updates?

**Pull request merged**
